export interface DouYinQuery {
	device_platform: string
	aid: string
	channel: string
	pc_client_type: number
	version_code: string
	version_name: string
	cookie_enabled: string
	screen_width: number
	screen_height: number
	browser_language: string
	browser_platform: string
	browser_name: string
	browser_version: string
	browser_online: string
	engine_name: string
	engine_version: string
	os_name: string
	os_version: string
	cpu_core_num: number
	device_memory: number
	platform: string
	downlink: string
	effective_type: string
	from_user_page: string
	locate_query: string
	need_time_list: string
	pc_libra_divert: string
	publish_video_strategy_type: string
	round_trip_time: string
	show_live_replay_strategy: string
	time_list_query: string
	whale_cut_token: string
	update_version_code: string
	msToken: string
	max_cursor: number
	count: number
	sec_user_id: string
}
